Mention users
activitypods/mastopod pull request #38
Opened 2024-11-26 17:26 UTC by SlyRock

closes #5 Mention users

Jest a draft PR so you may give your opinion at this stage :)

2024-11-26 18:43 UTC, srosset81 commented on frontend/src/common/blocks/ActivityBlock/Note.jsx
> +    content = content.replaceAll('\n', '<br>')
Cette ligne génère une erreur lorsque `content` est null. 
```suggestion
    content = content?.replaceAll('\n', '<br>')
```

2024-11-27 13:33 UTC, Laurin-W requested changes
Really nice feature! :)

2024-11-27 14:30 UTC, SlyRock commented on frontend/src/common/blocks/PostBlock.jsx
> +  const mentionables = useMemo(() => sortBy(uniqBy([...followers, ...following], 'id'), 'preferredUsername').map((actor) => {
Yes I chose not to add contacts to the list as they may not be Mastopod users.
Let's where #305 leads and we can make improvement here at that time :)

2024-11-27 14:45 UTC, SlyRock commented on frontend/src/hooks/useMentions/MentionsList.jsx
> +export default forwardRef((props, ref) => {
TBH I just repatriated this code from the `@semapps/activitypods-components` package in order to revive the useMentions hook as suggested by @srosset81 in issue #5 
I didn't take the necessary time to dif into the mechanics at play here but that code is the one given in the documentation of tiptap though : https://tiptap.dev/docs/editor/extensions/nodes/mention so I let it alone and move on with the rest of the task.

2024-11-27 14:46 UTC, SlyRock commented on frontend/src/hooks/useMentions/useMentions.js
> +const useMentions = data => {
will do 🙂

2024-11-28 09:01 UTC, srosset81 commented on frontend/src/hooks/useMentions/MentionsList.jsx
> +export default forwardRef((props, ref) => {
@Laurin-W forwardRef is a React function https://fr.react.dev/reference/react/forwardRef

2024-11-28 09:02 UTC, srosset81 commented on frontend/src/common/blocks/PostBlock.jsx
> +        const { processedContent, mentionedUsersUris } = processEditorContent(values.content);
Hmmm this code is inside a callback, I don't think we need (or even can) use useMemo

2024-11-28 09:11 UTC, srosset81 commented on frontend/src/common/blocks/PostBlock.jsx
> +  const { items: followers } = useCollection('followers', { dereferenceItems: true });
SPARQL query would only work with ActivityPods. And in ActivityPods, the followers/following lists are not paginated anyway. In ActivityPods 3.0 (and SemApps 2.0!), we plan to add [filtering on collection](https://github.com/assemblee-virtuelle/semapps/issues/1251), so this will certainly be the best option.

2024-11-28 15:26 UTC, Laurin-W commented on frontend/src/hooks/useMentions/MentionsList.jsx
> +export default forwardRef((props, ref) => {
Ahh, thanks! :sweat_smile:

2024-12-02 09:24 UTC, SlyRock commented on frontend/src/common/blocks/PostBlock.jsx
> +  const mentionables = useMemo(() => sortBy(uniqBy([...followers, ...following], 'id'), 'preferredUsername').map((actor) => {
Should we add contacts to the mentionnables when we're not sure they have mastopod installed ? What would be the result for them ?

2024-12-02 09:28 UTC, SlyRock commented on frontend/src/common/blocks/PostBlock.jsx
> +  const { items: followers } = useCollection('followers', { dereferenceItems: true });
So that means we don't need to worry about that right now ?
My understanding is that with what I did : 

1. we would get a full list for followers and following.
2. we are really under optimized as for users with long lists that would fetch a lot of data to be processed on the front end
3. We can optimize later when we have filtering on collections by modifying the `useMentions` to relay the query to the backend.

Did I get everything right according to you guys ? @srosset81 @Laurin-W

2024-12-02 09:56 UTC, srosset81 commented on frontend/src/common/blocks/PostBlock.jsx
> +  const mentionables = useMemo(() => sortBy(uniqBy([...followers, ...following], 'id'), 'preferredUsername').map((actor) => {
All users posting on Mastopod will necessarily have an ActivityPods account, so a `apods:contacts` collection attached to their WebID.

2024-12-02 10:00 UTC, srosset81 commented on frontend/src/common/blocks/PostBlock.jsx
> +  const { items: followers } = useCollection('followers', { dereferenceItems: true });
Indeed for `useMentions`, since we are fetching only our *own* followers/following list, it will never be paginated. We can think later about optimization.

2024-12-02 10:04 UTC, SlyRock commented on frontend/src/common/blocks/PostBlock.jsx
> +  const mentionables = useMemo(() => sortBy(uniqBy([...followers, ...following], 'id'), 'preferredUsername').map((actor) => {
Yes I know that but what about a user with an ActivityPods account, not using mastopod but being mentionned by one of his contacts ? How would he be notified ? Would he receive a mail and nicely be encouraged to use mastopod, for example ? I just want to make sure there isn't a hole in the logic here :)

2024-12-02 15:00 UTC, srosset81 approved these changes
I read the whole code and it is very clean, thank you !
Just one minor graphical thing: the public (earth) icon is green while the others are black. It would be better to have everything the same color (maybe black). Also there is a blank option that is useless (if you select it, it selects the public broadcast mode).
![Capture d’écran du 2024-12-02 15-51-04](https://github.com/user-attachments/assets/a1c27727-0243-47f8-8101-687481334909)

2024-12-02 16:25 UTC, srosset81 approved these changes

2024-12-02 16:27 UTC, merged